export const products = [
  {
    _id: "1",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-1",
    price_id: 2,
  },
  {
    _id: "2",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-2",
    price_id: 2,
  },
  {
    _id: "3",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-3",
    price_id: 2,
  },
  {
    _id: "4",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-4",
    price_id: 2,
  },
  {
    _id: "5",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-5",
    price_id: 2,
  },
  {
    _id: "6",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 6",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-6",
    price_id: 2,
  },
  {
    _id: "7",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 7",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-7",
    price_id: 2,
  },
  {
    _id: "8",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 8",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-8",
    price_id: 2,
  },
  {
    _id: "9",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 9",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-9",
    price_id: 2,
  },
  {
    _id: "10",
    image: "/demo.webp",
    price: 300,
    name: "Product Name 10",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    slug: "product-10",
    price_id: 2,
  },
];
